# Generated by Django 5.0.7 on 2024-08-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
                ('categoryStatus', models.CharField(choices=[('sus', 'suspended'), ('cont', 'continue')], default='cont', max_length=4)),
            ],
        ),
    ]
