# Generated by Django 5.0.7 on 2024-08-12 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(max_length=100)),
                ('min_qty', models.IntegerField()),
                ('max_qty', models.IntegerField()),
                ('instock_qty', models.IntegerField()),
                ('rack_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bin_no', models.CharField(blank=True, max_length=100, null=True)),
                ('item_status', models.CharField(blank=True, max_length=50)),
                ('item_nature', models.CharField(choices=[('sus', 'suspended'), ('cont', 'continue')], default='cont', max_length=4)),
                ('Category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.category')),
            ],
        ),
    ]
