# Generated by Django 5.0.7 on 2024-08-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='vendors', to='warehouse.category'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='vendors', to='warehouse.item'),
        ),
    ]
