# Generated by Django 5.0.7 on 2024-08-12 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_vendor_categories_vendor_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issueTo', models.CharField(max_length=100)),
                ('issue_to_dept', models.CharField(max_length=100)),
                ('qty_issued', models.IntegerField()),
                ('issueDate', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.category')),
                ('issueBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.item')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totalPrice', models.IntegerField()),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('expectedDeliveryDate', models.DateField()),
                ('receivingDate', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=100, null=True)),
                ('orderBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_by', to=settings.AUTH_USER_MODEL)),
                ('receiveBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receive_by', to=settings.AUTH_USER_MODEL)),
                ('vendorNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='ItemLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_balance', models.IntegerField()),
                ('balance_received', models.IntegerField()),
                ('balance_issued', models.IntegerField()),
                ('closing_balance', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('gate_pass_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.itemissue')),
                ('orderNo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_required', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=500, null=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.category')),
                ('item_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.item')),
                ('requestBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='requestID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.requests'),
        ),
    ]
